---
title: "logistic_classifier"
author: "Madison Yonash"
date: "2024-04-04"
output: html_document
---


```{r}
#install.packages("magick")
```

```{r}
library(tidyverse)
library(jpeg)
library(magick)
```



```{r}
# Set paths to cat and dog image folders
cat_folder <- "C:/Users/madis/Documents/ADV-DS-Project/kagglecatsanddogs_3367a/PetImageSample/Cat"
dog_folder <- "C:/Users/madis/Documents/ADV-DS-Project/kagglecatsanddogs_3367a/PetImageSample/Dog"
```


```{r}
# Function to load and preprocess images
load_image <- function(file_path) {
  img <- image_read(file_path)
  # Preprocess image (if necessary)
  return(img)
}

# Function to extract features from images
extract_features <- function(image) {
  # Convert image to grayscale and resize if necessary
  image <- image_convert(image, colorspace = "gray")
  image <- image_resize(image, "256x256")  # Adjust size as needed
  
  # Extract pixel values as a vector
  pixels <- as.numeric(image_data(image))
  
  # Return the vector of features
  return(pixels)
}
```



```{r}
cat_images <- list.files(cat_folder, full.names = TRUE) %>%
  lapply(load_image)
dog_images <- list.files(dog_folder, full.names = TRUE) %>%
  lapply(load_image)

```


```{r}
# Extract features from images
cat_features <- lapply(cat_images, function(image) extract_features(image))
dog_features <- lapply(dog_images, function(image) extract_features(image))
```

```{r}
# Create feature matrix X and target vector y
X <- rbind(do.call(rbind, cat_features), do.call(rbind, dog_features))
y <- c(rep(0, length(cat_features)), rep(1, length(dog_features)))
```

```{r}
# Train-test split
set.seed(69)
train_indices <- sample(1:length(y), 0.8 * length(y))
test_indices <- setdiff(1:length(y), train_indices)

X_train <- X[train_indices, ]
y_train <- y[train_indices]
X_test <- X[test_indices, ]
y_test <- y[test_indices]

```

```{r}
# Train logistic regression model
model <- glm(y_train ~ ., data = data.frame(cbind(y_train, X_train)), family = binomial)
```

```{r}
# Evaluate model 
predictions <- predict(model, newdata = data.frame(X_test), type = "response")
threshold <- 0.5  # Threshold for binary classification
accuracy <- mean(ifelse(predictions >= threshold, 1, 0) == y_test)
print(paste("Accuracy:", accuracy))
```










