---
title: "ADV DS Report"
output: html_notebook
---

# Introduction 

As the project for **CAP 4793 Advanced Data Science** was very open-ended, our team wanted to choose a project that encompasses both something that interests us and something that would challenge us to do something new. 

# Data Description
This data set includes 25,000 images that are a subset of three million annotated images compiled by Petfinder.com and Microsoft. These 25000 images are spit into two classes. These classes are not split into training and testing sets, but separated based on if they are a cat or dog. For a more realistic model many of the images have additional noise or obstructions in the images. Because of this additional noise this data set is not uniform.

# Exploratory Data Analysis

# Modeling

# Web App

# Conclusion
With this model created we achieved an 84 percent accuracy. This accuracy in the model could be due to several reasons. Some such reasons could be lighting, angle, shape, and additional noise affected the models view of the animal. In order to achieve this model a flask app implemented in python was used since there were more resources found with that. A custom network was created from two Kaggle examples that were found since these examples had previously been ran with a high accuracy probability. In all this is a fairly custom model based on existing and proven models seen to work in the past. 

# Future Work
For future work, we would like to view different kinds of models and neural networks to compare the results. With this comparison, continue to improve upon and adjust the current model. As we improve on the model we wish to add in more data as this is only a very small subset of the full data-set of three million images. We eventually wish to explore more image pre-processing techniques to see if it works better with the model. And finally, we could add in an "other" option if the probability of an image being a cat or a dog is close (for example 55 - 45) as this image could be hard to view even for humans let alone this model.
